name: 'Actionlint Action'
description: 'Install actionlint and run it on all workflow files'
author: 'eifinger'
inputs:
  version:
    description: 'The version of actionlint to install'
    required: false
    default: '1.7.6'
  checksum:
    description: 'The checksum of the actionlint binary'
    required: false
runs:
  using: composite
  steps:
    - name: Install actionlint
      run: |
        case "$OSTYPE" in
            linux-*)
                os=linux
                ext=tar.gz
            ;;
            darwin*)
                os=darwin
                ext=tar.gz
            ;;
            freebsd*)
                os=freebsd
                ext=tar.gz
            ;;
            msys|cygwin|win32)
                os=windows
                ext=zip
            ;;
            *)
                echo "OS '${OSTYPE}' is not supported. Note: If you're using Windows, please ensure bash is used to run this script" >&2
                exit 1
            ;;
        esac


        machine="$(uname -m)"
        case "$machine" in
            x86_64) arch=amd64 ;;
            i?86) arch=386 ;;
            aarch64|arm64) arch=arm64 ;;
            arm*) arch=armv6 ;;
            *)
                echo "Could not determine arch from machine hardware name '${machine}'" >&2
                exit 1
            ;;
        esac

        echo "Detected OS=${os} ext=${ext} arch=${arch}"

        file="actionlint_${VERSION}_${os}_${arch}.${ext}"
        url="https://github.com/rhysd/actionlint/releases/download/v${VERSION}/${file}"
        curl -L -o "${file}" "${url}"
        if ! sha256sum -c ${GITHUB_ACTION_PATH}/checksums.txt --ignore-missing --status;
        then
          echo "No known checksum matches. Checking for supplied checksums..."
          if [[ ! -z "$CHECKSUM" ]]; then
            echo "${CHECKSUM}  ${file}" | sha256sum -c
          else
            echo ::warning title=Unvalidated binary::No checksums could be found to validate ${file}. Please consider adding a checksum via the checksum input.
          fi
        fi
        if [[ "$os" == "windows" ]]; then
            unzip "${file}" actionlint.exe
        else
            tar xzf "${file}" actionlint
        fi
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        CHECKSUM: ${{ inputs.checksum }}
    - name: Add Matcher
      run: echo "::add-matcher::${GITHUB_ACTION_PATH}/matchers/actionlint.json"
      shell: bash
    - name: Lint GitHub Action Workflows
      run: ./actionlint -color
      shell: bash
branding:
  icon: 'check'
  color: 'green'
