name: 'Actionlint Action'
description: 'Install actionlint and run it on all workflow files'
author: 'eifinger'
inputs:
  version:
    description: 'The version of actionlint to install'
    required: false
    default: '1.6.25'
  checksum:
    description: 'The checksum of the actionlint binary'
    required: false
runs:
  using: composite
  steps:
    - name: Install actionlint
      run: |
        file="actionlint_${VERSION}_linux_amd64.tar.gz"
        url="https://github.com/rhysd/actionlint/releases/download/v${VERSION}/${file}"
        curl -L -o "${file}" "${url}"
        if [[ ! -z "$CHECKSUM" ]]; then
          echo "${CHECKUM}  ${file}" | sha256sum
        fi
        tar xzf "${file}" actionlint
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        CHECKSUM: ${{ inputs.checksum }}
    - name: Add Matcher
      run: echo "::add-matcher::./matchers/actionlint.json"
      shell: bash
    - name: Lint GitHub Action Workflows
      run: ./actionlint -color
      shell: bash
branding:
  icon: 'check'
  color: 'green'
